FROM postgres:latest

# Устанавливаем переменные окружения для подключения к базе данных
ENV POSTGRES_USER=${DB_USERNAME}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}
ENV POSTGRES_DB=${DB_NAME}
ENV POSTGRES_HOST=${DB_HOST}
ENV POSTGRES_PORT=${DB_PORT}

ENV POSTGRES_INITDB_ARGS="--locale=en_US.utf8"
EXPOSE ${DB_PORT}

CMD ["postgres"]